### ISSUE TITLE
stickyTable header flickering on mouse scroll in IE 11 

### ISSUE THREAD

**Issue by rvaishnavq3** [armaaar/JQuery-Sticky-Table#1]
when i just scroll down with the help of mouse wheel, the sticky header flickering in IE only, please have a look on attached screenshot. Thanks

![ie11-issue](https://user-images.githubusercontent.com/35262193/34722312-5a039850-f56c-11e7-90af-298f4b885eb3.jpg)

**Comment by armaaar** [comment]
This problem can only be reproduced by giving `.sticky-table` or its `<table>` a `padding-top` attribute or making the `<table>` have a `border-collapse: separate` while having a padding.

Anyway, I updated all CSS files to prevent this from happening again. 
@rvaishnavq3 Please download the new `jquery.stickytable.min.css` or `jquery.stickytable.css` and clear your browser cache and try again.

**Comment by rvaishnavq3** [comment]
Thanks For your quick response, but I had updated the CSS files (jquery.stickytable.css) but its not working for me. your demo html file is also not working in IE 11, here is I made a small video please have a look on it.
Click on the link below-
https://www.screencast.com/t/mNDTJgFH

Going forward to your next suggestion.
![ie11-issue-1 1](https://user-images.githubusercontent.com/35262193/34759834-5ab78cec-f603-11e7-8943-2ec971ea3696.jpg)

**Comment by armaaar** [comment]
After IE11 crashed for several times I found the problem. Smooth scrolling in IE11 is causing this issue, I could fix this problem in IE11 when scrolling using mouse wheel or scroll bar But for sorry couldn't find a solution for it if the user scrolled using scrollbar arrows.

@rvaishnavq3 Please download the new `jquery.stickytable.min.js` or `jquery.stickytable.js` and clear your browser cache and inform me if the problem is gone.

**Comment by rvaishnavq3** [comment]
ok Thanks @armaaar , let it be its fine for me Thanks again for your support

**Comment by Sudeep2443** [comment]
@armaaar, I had updated the CSS and JS files too, but its not working for me. your demo html file is also not working in IE 11 and also in Firefox. Also i had clear browser cache, still its not working header flickering is still coming. I am using this plugin [https://www.jqueryscript.net/table/jQuery-Plugin-For-Sticky-Table-Cells-stickyTable-js.html] Your solution doesn't solve the issue.

Please let me know if any update is there for this.
Thanks.

**Comment by armaaar** [comment]
@Sudeep2443 I couldn't reproduce any problem on IE11. There is a known issue in Firefox <= v57.0 and Microsoft Edge in the way they implement the scroll event. Microsoft edge promised to solve this problem in the upcoming version Edge 17672.

**Comment by Sudeep2443** [comment]
Hello @armaaar Thanks for a quick response, here is I made a small video please have a look on it.
Click on the link below-
(url https://www.screencast.com/t/AxbtzV4VIxW)

Click on below link for plugin which i have used currently 
(url https://www.jqueryscript.net/table/jQuery-Plugin-For-Sticky-Table-Cells-stickyTable-js.html)

Same happening in this plugin, Please click on below link for video
(url https://www.screencast.com/t/HxgAavuniLt)

Its still not working in IE 11 and also in firefox 61.0.2 (32-bit).
Please guide.

**Comment by Sudeep2443** [comment]
@armaaar Any update?

**Comment by armaaar** [comment]
@Sudeep2443 Please download the latest version of the plugin from this repository. This will fix the firefox problems. In case of IE11 the smooth scrolling feature causes the cells to lag and flicker so we had to disable it which caused some roughness or delay in scrolling but It works fine. I'm sorry but at the moment there is no other solutions for IE11. I'll let you know if there is any major update for IE11

**Comment by Sudeep2443** [comment]
@armaaar I had downloaded your latest version of the plugin but it doesn't work for me in new version of Firefox but its work fine in old version.
Please guide.

**Comment by armaaar** [comment]
@Sudeep2443 Please create a new Issue for your problem in firefox with detailed description of your problem so I can help. Also make sure you cleared your cache after using the new css and js files
