### ISSUE TITLE
stickyTable header and left column flickering on scroll in Firefox old version (57.0.2) 

### ISSUE THREAD

**Issue by rvaishnavq3** [armaaar/JQuery-Sticky-Table#2]
Now its header and freeze column flickering in Firefox (version 57.0.2) and i am stuck bcoz of this, , Can you please have a look on this issue,  Please have a look on this small video.

https://www.screencast.com/t/r5egU0o7uQl

**Comment by armaaar** [comment]
I tried every possible thing. I slowed the scrolling and disabled the smooth scrolling feature in firefox. I found no effective solution for this. and the problem disappears completely once I open Developer Tools.

In the other hand the flickering happens so fast and doesn't affect the functionality not the user experience greatly. so I think users with old browsers will have to deal with this small flickering for now.

sorry but I have no fix for this issue.

**Comment by rvaishnavq3** [comment]
In Firefox 58.01.1 Sticky Header is flickering and Left freeze column is also not working, but when i open fire bug Sticky Header is working fine but left freeze column still remain same and if I close fire bug The issue will come again.

Can you please look on it as my client normally check my site in FF.

**Comment by armaaar** [comment]
It's the same Issue with FF 57.0.2 with the same behavior. I'll reopen this issue and give it a second shot.

**Comment by armaaar** [comment]
Unfortunately this problem happen due to the fact that Firefox handles scroll asynchronously.
[https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects)

> Often scrolling effects are implemented by listening for the scroll event and then updating elements on the page in some way (usually the CSS position or transform property.) [...]
> 
> These effects work well in browsers where the scrolling is done synchronously on the browser's main thread. However, most browsers now support some sort of asynchronous scrolling in order to provide a consistent 60 frames per second experience to the user. In the asynchronous scrolling model, the visual scroll position is updated in the compositor thread and is visible to the user before the scroll event is updated in the DOM and fired on the main thread. This means that the effects implemented will lag a little bit behind what the user sees the scroll position to be. This can cause the effect to be laggy, janky, or jittery — in short, something we want to avoid.
> 

I'm searching for a way to disable asynchronous scroll behaviour using js. If no one could be found I'll have to close this issue as there is no solution to it.

**Comment by armaaar** [comment]
This issue is resolved. for anyone facing this issue please download the newest version of the plugin and clear your browser cache as well.
