### ISSUE TITLE
Help: Fixed footer doesn't work

### ISSUE THREAD

**Issue by coy102** [armaaar/JQuery-Sticky-Table#4]
![image](https://user-images.githubusercontent.com/13234170/41952534-9cebba68-79fa-11e8-9d1c-c27750d0a5b2.png)

hello, sticky for tfoot doesn't work, 

Here the code
`  <tfoot>
                    <tr class="sticky-row">
                        <td class="sticky-cell">F1212ord</td>
                        <td class="sticky-cell">Escort</td>
                        <td>Blue</td>
                        <td>2000</td>
                        <td>Ford</td>
                        <td>Escort</td>`

**Comment by coy102** [comment]
i hope you can help me, thanks

**Comment by armaaar** [comment]
@coy102 I'm adding the feature of having sticky footers now

**Comment by armaaar** [comment]
I've added the ability to add sticky footers and opposite side sticky columns as well. some changes has been done to the classes names so you would need to read the [how to use](https://github.com/armaaar/JQuery-Sticky-Table#how-to-use-sticky-table) section again.
@coy102 Please download the newest version of the plugin clear your browser cache as well.
