### ISSUE TITLE
StickyTable header flickering on Scroll in Firefox 62.0 (32-bit)

### ISSUE THREAD

**Issue by Sudeep2443** [armaaar/JQuery-Sticky-Table#5]
@armaaar Replaced with the latest css and js and also cleared the cache before checking but still facing issue while scrolling in Mozilla (Firefox version 62) and 32 bits Window 8.

**PLEASE TAKE A NOTE**:  Working fine in Linux Mozilla (Firefox version 43).

Here is the small video of not working demo, Please have look on it:
(url https://www.screencast.com/t/gjLCe87gQr)

Please Find JS and CSS attach in zip file which we have used in the demo.
[Used-css-js.zip](https://github.com/armaaar/JQuery-Sticky-Table/files/2366028/Used-css-js.zip)

**Comment by armaaar** [comment]
Sorry for late reply
those are not the latest js and css files.
please use these files instead
[sticky.zip](https://github.com/armaaar/JQuery-Sticky-Table/files/2385813/sticky.zip)

inform me if your issue is resolved

**Comment by armaaar** [comment]
Tested for Firefox version 62 and works fine.

**Comment by Sudeep2443** [comment]
@armaaar  Thanks for your reply,
Is it working in Edge and IE11 in your?
Coz its still having same issue with me.

**Comment by armaaar** [comment]
Sorry for the late response as I'm not available most of the time for now
Can you provide a screenshot or a video of the problem?

**Comment by Sudeep2443** [comment]
@armaaar I already created new issue with named "Sticky Table Reload in EDGE While Inspecting the content in table", I have also provided video for that.
