### ISSUE TITLE
Multiple sticky-cells

### ISSUE THREAD

**Issue by yapsr** [armaaar/JQuery-Sticky-Table#7]
Multiple sticky cells float over each other. How to prevent this and stack these cells next to each other?

**Comment by armaaar** [comment]
Can you provide a screenshot and code snippet? or at least describe what you are trying to accomplish

**Comment by yapsr** [comment]
<div class="sticky-table">
	    <table class="sticky-table">
	        <tr>
	            <td class="sticky-cell">First Sticky Cell</td>
	            <td class="sticky-cell">Second Sticky Cell</td>
	            <td>Third Regular Cell</td>
	        </tr>
	    </table>
	</div>

When scrolling to the right, the Sticky Cells move to the left and then the second cell floats over the first one. This probably is the way the CSS 'position: sticky' works, but that is not my intention. I would like the sticky cells to remain visible next to each other, like in this example with another library: https://jsfiddle.net/2oj9c5q2/21

If tried to fix this by dynamically setting the 'left' offset of the cell styles in javascript, based on the width of the cell:

	var $ths = $.('th.sticky-cell');
	var offset = 0;
	var css = '';
	$ths.each(function (idx, el) {
	    var $this = $(el);
	    css += '.sticky-table.sticky-ltr-cells table th.sticky-cell:nth-of-type(' + (idx + 1) + '),';
	    css += '.sticky-table.sticky-ltr-cells table td.sticky-cell:nth-of-type(' + (idx + 1) + ') {';
	    css += '   left: ' + offset + 'px;';
	    css += '}';
	    offset += $this.width();
	})
	css = '<style type="text/css">' + css + '</style>';
	$(css).appendTo("head");


But I wonder if I could fix it with some easy CSS or if this could be a feature of your library.

**Comment by armaaar** [comment]
Sorry for late response. You are right. For now, you can't use multiple sticky cells using this plugin. also I've tried multiple css workarounds with no luck. But your solution is actually brilliant and we could use it in the next version of the plugin. I should actually thank you!

**Comment by armaaar** [comment]
Sorry for taking about a year to revisit issues in this plugin.

I've add the feature you suggested to all `sticky-header`, `sticky-footer`, `sticky-cell` and `sticky-cell-opposite` for both `sticky-ltr-cells` and `sticky-rtl-cells` using the same method you proposed for browsers that supports `position:sticky`.

Now you can stack sticky rows and cells next to each other.
